package com.ainexus.entity;

public enum AuditActionType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    AUTHORIZATION_DENIED,
    DOCUMENT_UPLOAD,
    DOCUMENT_DELETE,
    DOCUMENT_ACCESS,
    WORKSPACE_CREATED,
    WORKSPACE_UPDATED,
    WORKSPACE_MEMBER_ADDED,
    WORKSPACE_MEMBER_REMOVED,
    USER_CREATED,
    USER_UPDATED,
    ROLE_CHANGED,
    STATUS_CHANGED,
    WORKFLOW_EXECUTED,
    WORKFLOW_APPROVAL,
    SCHEDULE_TRIGGERED,
    AI_INFERENCE_REQUESTED,
    AI_QUOTA_EXCEEDED,
    ADMIN_CONFIG_CHANGED,
    SECURITY_ALERT
}
